### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by startergo** [cdf/NightShiftEnabler#1]
I get an error during compilation:

[Error.txt](https://github.com/cdf/NightShiftEnabler/files/5445500/Error.txt)
These are my compilation settings. Everything else builds
[OCkextsLilu.command.zip](https://github.com/cdf/NightShiftEnabler/files/5445507/OCkextsLilu.command.zip)

**Comment by startergo** [comment]
It looks like in Lilu's kern_api_h:
https://github.com/acidanthera/Lilu/blob/master/Lilu/Headers/kern_api.hpp#L21
```
#ifndef __ACIDANTHERA_MAC_SDK
#error "This kext SDK is unsupported. Dowload from https://github.com/acidanthera/MacKernelSDK"
#endif
```
https://www.insanelymac.com/forum/topic/321371-lilu-%E2%80%94-kext-and-process-patcher/?do=findComment&comment=2742264

**Comment by EETagent** [comment]
Yes, just add MacKernelSDK to the project, every step is in their README. After that it will compile successfully
