### ISSUE TITLE
Not working with Big Sur 11.1

### ISSUE THREAD

**Issue by RicheeThree** [cdf/NightShiftEnabler#3]
I am using OpenCore 0.6.4 and this. Night Shift is not available from the Display preferences. Not sure if this is a goal of this project, but it seems that it might not be too far away? I'm not sure. Wanted to report here just in case.

**Comment by cdf** [comment]
I've updated the readme to clarify supported macOS versions: NightShiftEnabler depends on Lilu's userspace patching, which unfortunately does not currently work in Big Sur.

**Comment by vit9696** [comment]
@cdf we do not plan advanced patching APIs for Big Sur in the nearest future as Apple considerably limited our abilities. However, can still implement userspace patching manually similarly to this kext: https://github.com/osy/Polaris22Fixup

**Comment by cdf** [comment]
The plugin has been rewritten for Big Sur compatibility.

**Comment by RicheeThree** [comment]
Thank you!
