### ISSUE TITLE
NightShift Support only appearing in Control Centre

### ISSUE THREAD

**Issue by khronokernel** [cdf/NightShiftEnabler#6]
Apologies if this is already a known issue, had serval users report that NightShift support on unsupported models doesn't appear in Display Settings however does in Control Centre and in-fact functions:

| Control Centre | Display Settings | 
| :--- | :--- |
| ![Screen Shot 2021-05-09 at 10 12 13 AM](https://user-images.githubusercontent.com/48863253/117579321-8e69dd00-b0af-11eb-9eba-80a8ba94bd8a.png) | ![Screen Shot 2021-05-09 at 10 12 38 AM](https://user-images.githubusercontent.com/48863253/117579334-a17cad00-b0af-11eb-838f-cd052bcd6a35.png)

Verified that the patch does apply:

```
Lilu                    api: @ (DBG) got load request from NightShiftEnabler (110)
NightShiftEnabler       init: @ (DBG) NightShiftEnabler bootstrap DBG-110-2021-01-31
NightShiftEnabler       nse: @ (DBG) chosen shared cache path is /System/Library/dyld/dyld_shared_cache_x86_64
NightShiftEnabler       nse: @ (DBG) activating
NightShiftEnabler       nse: @ (DBG) patched Night Shift
```
* [Lilu Boot Log.txt](https://github.com/cdf/NightShiftEnabler/files/6448008/Lilu_1.5.2_20.4.txt)

This is replicable on multiple machines include iMac8,1, iMac11,2, MacBook7,1, MacBookPro6,2 and MacBookPro8,1. Unfortunately was unable to determine whether Mac Pros replicate this issue.

An odd extra note is that even when using a full SMBIOS replacement to a supported SMBIOS, Display Settings would still be omitted. I even verified on my X299 Hackintosh with a 5700XT and the NightShift entry is still missing. This would lead me to believe there's a display panel check in the OS whether it'll appear, and if there's a supported display it will allow the option:

<img width="780" alt="Screen Shot 2021-05-09 at 10 36 02 AM" src="https://user-images.githubusercontent.com/48863253/117579912-721b6f80-b0b2-11eb-9114-9b7c4eed4cf1.png">

Overall this is not a very important issue, though mostly wished to bring to light in case this hasn't been discussed yet

**Comment by cdf** [comment]
Thanks for the report. On the Mac Pro 5,1, the patch effectively enables the option in Display Settings:
<img width="780" alt="Night Shift" src="https://user-images.githubusercontent.com/63161650/117580665-07c0fa00-b0c7-11eb-92b8-f0e784a3a40b.png">
The only check that I am aware of for Night Shift is done by a function in CoreBrightness that compares the model identifier against a list of minimum supported models. NightShiftEnabler simply sets all model versions to 1 for the check to pass. I know that Night Shift doesn't work for all external displays, so it would make sense that there is another check somewhere.

Userspace patching in Big Sur is rather aggressive: the patch is applied while the code is running and therefore should apply to all processes that call the function. So it seems that there is indeed another check. But just to be sure, perhaps we could verify that applying the same patch manually suffers from the same shortcoming.

> An odd extra note is that even when using a full SMBIOS replacement to a supported SMBIOS, Display Settings would still be omitted. I even verified on my X299 Hackintosh with a 5700XT and the NightShift entry is still missing.

Interesting. Does the option appear in Control Center, though?

**Comment by khronokernel** [comment]
> Interesting. Does the option appear in Control Center, though?

Control Centre entry appears and works which is quite odd. I did a bit more testing and found that on macOS 10.15.6 with my X299 machine, Night Shift in-fact appears in Display Settings:

<img width="780" alt="Screen Shot 2021-05-09 at 12 48 09 PM" src="https://user-images.githubusercontent.com/48863253/117583554-f8d94800-b0c4-11eb-8d3f-9f2c21662b37.png">

Based off this, it seems to be more of a Big Sur bug and not intended behaviour at least from what I can tell as well as the information you provided with your Machine working.

**Comment by khronokernel** [comment]
Update: Apparently the entry magically appeared in Big Sur after rebooting to Catalina and back, so it is an Apple bug that the entry disappears. Closing and thanks for your time on this issue!
