### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by ellaosx2007** [cdf/NightShiftEnabler#9]
Hi @cdf 
In Sierra & High Sierra, it panics with lilu 1.5.8 & 1.5.7. Last working lilu version was 1.5.6.
Mojave & above are ok.

**Comment by ThiagodelaT** [comment]
Hi @cdf it also panics with lilu 1.5.8 in OC 0.7.6 in Mojave for me.
![Screen Shot 2021-12-21 at 23 41 50](https://user-images.githubusercontent.com/96515180/147045924-d4d9df84-80b8-4b12-9aa3-30e44825b740.png)

**Comment by cdf** [comment]
Could you provide a panic log with the keepsyms=1 boot argument? There seems to be an issue with [hooking `cs_validate_range`](https://github.com/acidanthera/bugtracker/issues/1898).

**Comment by ThiagodelaT** [comment]
I sure can, but I need a little bit of help, I'm not that well versed with this...
I think I should add it in this string:

<key>boot-args</key>
				<string>-lilubetaall -wegbeta agdpmod=pikera shikigva=80 unfairgva=1 mbasd=1 -wegtree -no_compat_check no32exec=0</string>

But not sure if position/order matters, can you point me to the correct aproach?
Right now I'm using MartinLo´'s package for the 4,1/5,1 so another option could be if you link a config.plist modified with all you need for me to try.

**Comment by cdf** [comment]
You can just add it to the string in your config. Order doesn't matter.

**Comment by ThiagodelaT** [comment]
panic(cpu 2 caller 0xffffff80082dab9d): Kernel trap at 0xffffff8008706c8b, type 6=invalid opcode, registers:
CR0: 0x0000000080010033, CR2: 0x00007ffee4831e88, CR3: 0x00000001b60a4002, CR4: 0x00000000000226e0
RAX: 0x1497857c1176007c, RBX: 0xffffff80962336c8, RCX: 0xfffffeb9dbfeb000, RDX: 0x0000000000002000
RSP: 0xffffff872ccc31d8, RBP: 0xffffff872ccc31e0, RSI: 0xffffff809624c690, RDI: 0xffffff80962336c8
R8:  0x0000000000001000, R9:  0xffffff872ccc3674, R10: 0x0000000000000000, R11: 0x00000001b60a4000
R12: 0xffffff801bf98f38, R13: 0xffffff801bf98f64, R14: 0x0000000000001000, R15: 0xfffffeb9dbfeb000
RFL: 0x0000000000010202, RIP: 0xffffff8008706c8b, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x00007ffee4831e88, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 0

Backtrace (CPU 2), Frame : Return Address
0xffffff872ccc2ca0 : 0xffffff80081ad5cd mach_kernel : _handle_debugger_trap + 0x47d
0xffffff872ccc2cf0 : 0xffffff80082e9245 mach_kernel : _kdp_i386_trap + 0x155
0xffffff872ccc2d30 : 0xffffff80082da97a mach_kernel : _kernel_trap + 0x50a
0xffffff872ccc2da0 : 0xffffff800815a9d0 mach_kernel : _return_from_trap + 0xe0
0xffffff872ccc2dc0 : 0xffffff80081acfe7 mach_kernel : _panic_trap_to_debugger + 0x197
0xffffff872ccc2ee0 : 0xffffff80081ace33 mach_kernel : _panic + 0x63
0xffffff872ccc2f50 : 0xffffff80082dab9d mach_kernel : _kernel_trap + 0x72d
0xffffff872ccc30c0 : 0xffffff800815a9d0 mach_kernel : _return_from_trap + 0xe0
0xffffff872ccc30e0 : 0xffffff8008706c8b mach_kernel : _cs_validate_range + 0xb
0xffffff872ccc31e0 : 0xffffff7f8c7ffc3f com.cdf.NightShiftEnabler : __ZN17NightShiftEnablerC2Ev + 0x3df
0xffffff872ccc3630 : 0xffffff7f8c763056 as.vit9696.Lilu : __ZN11UserPatcher14injectRestrictEP8ipc_port + 0x526
0xffffff872ccc3660 : 0xffffff800823a281 mach_kernel : _vm_page_validate_cs_mapped_slow + 0x81
0xffffff872ccc3680 : 0xffffff800823a130 mach_kernel : _vm_page_validate_cs + 0x120
0xffffff872ccc36b0 : 0xffffff8008238f51 mach_kernel : _vm_fault_enter + 0x2f1
0xffffff872ccc3800 : 0xffffff800823ba9a mach_kernel : _vm_pre_fault + 0x17ea
0xffffff872ccc39d0 : 0xffffff80086b1b0b mach_kernel : _kctl_fill_socketinfo + 0x2a2b
0xffffff872ccc3d20 : 0xffffff80086b6802 mach_kernel : _posix_spawn + 0x2de2
0xffffff872ccc3da0 : 0xffffff80086b7857 mach_kernel : ___mac_execve + 0x227
0xffffff872ccc3e40 : 0xffffff80086b7eac mach_kernel : _load_init_program + 0x1dc
0xffffff872ccc3ec0 : 0xffffff800867cf6d mach_kernel : _bsdinit_task + 0x6d
0xffffff872ccc3ee0 : 0xffffff80086d4de0 mach_kernel : _bsd_ast + 0x3f0
0xffffff872ccc3f30 : 0xffffff80081a5629 mach_kernel : _ast_taken_user + 0xf9
0xffffff872ccc3f70 : 0xffffff800815a99c mach_kernel : _return_from_trap + 0xac
      Kernel Extensions in backtrace:
         as.vit9696.Lilu(1.5.8)[3E44E561-C07C-31E8-B2D7-0F31B5266E45]@0xffffff7f8c751000->0xffffff7f8c77bfff
         com.cdf.NightShiftEnabler(1.1.1)[0FB132F2-2689-33E1-92DD-B250BC5708D4]@0xffffff7f8c7ff000->0xffffff7f8c805fff
            dependency: as.vit9696.Lilu(1.5.8)[3E44E561-C07C-31E8-B2D7-0F31B5266E45]@0xffffff7f8c751000

BSD process name corresponding to current thread: init
Boot args: keepsyms=1 -lilubetaall -wegbeta agdpmod=pikera shikigva=80 unfairgva=1 mbasd=1 -wegtree -no_compat_check no32exec=0

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64
Kernel UUID: 041B6A6D-CD16-36FA-88B9-E32FF46EF89F
Kernel slide:     0x0000000007e00000
Kernel text base: 0xffffff8008000000
__HIB  text base: 0xffffff8007f00000
System model name: MacPro5,1 (Mac-7BA5B2D9E42DDD94)

System uptime in nanoseconds: 9616777450
last loaded kext at 2275289014: >!UDisplays	380 (addr 0xffffff7f8915d000, size 20480)
loaded kexts:
com.cdf.NightShiftEnabler	1.1.1
as.vit9696.WhateverGreen	1.5.5
as.vit9696.Lilu	1.5.8
>!UDisplays	380
>!AFileSystemDriver	3.0.1
>!AVirtIO	2.1.3
@filesystems.hfs.kext	407.200.4
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!ASystemPolicy	1.0
|SCSITaskUserClient	408.250.3
>!AFWOHCI	5.6.0
@filesystems.apfs	945.275.10
>!I82574LEthernet	2.7.2
@private.KextAudit	1.0
>!AAHCIPort	329.260.5
>!AHPET	1.8
>!ARTC	2.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
>!A!ICPUPowerManagementClient	220.0.0
@nke.applicationfirewall	202
$TMSafetyNet	8
>!A!ICPUPowerManagement	220.0.0
>!UAudio	315.6
>usb.IOUSBHostHIDDevice	1.2
|IOAudio!F	206.5
@vecLib.kext	1.2.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>usb.!UHub	1.2
|IOSerial!F	11
@filesystems.hfs.encodings.kext	1
|IOSCSIMultimediaCommandsDevice	408.250.3
|IOBD!S!F	1.8
|IODVD!S!F	1.8
|IOCD!S!F	1.8
|IOAHCISerialATAPI	267.50.1
|IOAHCIBlock!S	301.270.1
|IOFireWire!F	4.7.3
>!AXsanScheme	3
>!UMergeNub	900.4.2
|IOAHCI!F	288
>usb.!UEHCIPCI	1.2
>usb.!UUHCIPCI	1.2
>usb.!UUHCI	1.2
>usb.!UEHCI	1.2
|IONVMe!F	2.1.0
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!UHostMergeProperties	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	3
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	456.260.3
>!AMobileFileIntegrity	1.0.5
|IOUSBMass!SDriver	145.200.2
|IOSCSIBlockCommandsDevice	408.250.3
|IOSCSIArchitectureModel!F	408.250.3
|IO!S!F	2.1
@kext.CoreTrust	1
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOReport!F	47
|IOTimeSync!F	740.2
|IONetworking!F	3.4
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	1.0

**Comment by cdf** [comment]
This seems to be the same issue as discussed on the Acidanthera bugtracker. Since the issue may be related to Lilu, it's probably best to wait and see how it's handled there...

**Comment by ellaosx2007** [comment]
Solved by Lilu's latest commit (Jan 4, 2022)
